(openthread) [posix-app] fix missing sentinel in execl() (#4007)
This commit fixes a build error on OpenWRT.

Error: missing sentinel in function execl.